version: '3.1'
services:
  db-favourite-service:
    image: postgres:latest
    hostname: db-favourite-service
    container_name: db-favourite-service
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
      POSTGRES_DB: favourite
    ports:
      - 54321:5432
    volumes:
       - postgres_favourite:/data/postgres

  favourite-service:
    image: diyset/favourite-service:master-latest
    hostname: favourite-service
    container_name: favourite-service
    environment:
      DEBUG: false
      DB_PORT: 5432
      DB_HOST: db-favourite-service
      DB_ENGINE: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: favourite
      DB_DDL: update
      SPRING_PROFILES_ACTIVE: docker
      PORT: 8080
    ports:
      - 9206:8080
    command: --spring.profiles.active=docker
    depends_on:
      - db-favourite-service
     
volumes:
  postgres_favourite:

